AWSTemplateFormatVersion: "2010-09-09"
Description: Resources needed to deploy House Finder project
Parameters:
  newFileName:
    Type: String
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: house-finder-lambda
      Description: House Finder Lambda function
      Runtime: nodejs16.x
      Role: arn:aws:iam::770653768231:role/service-role/house-finder-lambda-role-9aq25b46
      Handler: index.handler
      Code:
        S3Bucket: house-finder-bucket
        S3Key: !Ref "newFileName"
      Timeout: 59
      MemorySize: 128
      TracingConfig:
        Mode: Active
  ScheduledRule:
    Type: AWS::Events::Rule
    DependsOn: LambdaFunction
    Properties:
      Name: house-finder-event-rule
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 hour)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "LambdaFunction"
              - "Arn"
          Id: "TargetFunc"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunction
    Properties:
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
